QT.dtkgui.VERSION = 5.6.8
QT.dtkgui.MAJOR_VERSION = 5
QT.dtkgui.MINOR_VERSION = 6
QT.dtkgui.PATCH_VERSION = 8
QT.dtkgui.name = dtkgui
QT.dtkgui.module = dtkgui
QT.dtkgui.tools = /runtime/lib/x86_64-linux-gnu/dtk5/DGui/bin
QT.dtkgui.libs = /runtime/lib/x86_64-linux-gnu
QT.dtkgui.includes = /runtime/include/dtk5/DGui
QT.dtkgui.frameworks =
QT.dtkgui.depends = core gui dtkcore gui_private dbus network
QT.dtkgui.module_config = v2 internal_module ltcg
QT.dtkgui.DEFINES = 
QT_MODULES += 
