QT.dtkcommon.VERSION = 5.6.8
QT.dtkcommon.MAJOR_VERSION = 5
QT.dtkcommon.MINOR_VERSION = 6
QT.dtkcommon.PATCH_VERSION = 8
QT.dtkcommon.name = dtkcommon
QT.dtkcommon.module = dtkcommon
QT.dtkcommon.tools = /runtime/lib/x86_64-linux-gnu/libdtk-5.6.8
QT.dtkcommon.libs = /runtime/lib/x86_64-linux-gnu
QT.dtkcommon.includes = /runtime/include/libdtk-5.6.8
QT.dtkcommon.frameworks = 
QT.dtkcommon.depends = xml
QT.dtkcommon.module_config = v2
QT.dtkcommon.DEFINES = 
QT_MODULES += 
